import type { ImgHTMLAttributes } from 'react';
import type { ImageAsset } from '../types.ts';

interface AppImageProps
  extends Omit<ImgHTMLAttributes<HTMLImageElement>, 'src' | 'srcSet' | 'width' | 'height' | 'alt'> {
  image: ImageAsset;
  alt: string;
  /** Above-the-fold image: eager loading and high fetch priority. */
  priority?: boolean;
}

/** Responsive <img> for assets generated by scripts/optimize-images.mjs. */
export function AppImage({
  image,
  alt,
  priority = false,
  sizes = '(min-width: 1024px) 50vw, 100vw',
  loading,
  decoding,
  ...rest
}: AppImageProps) {
  return (
    <img
      src={image.src}
      srcSet={image.srcSet}
      sizes={sizes}
      width={image.width}
      height={image.height}
      alt={alt}
      loading={loading ?? (priority ? 'eager' : 'lazy')}
      decoding={decoding ?? 'async'}
      fetchPriority={priority ? 'high' : undefined}
      {...rest}
    />
  );
}
