// Generates responsive WebP variants in public/images and the typed IMAGES map in src/data/images.ts.
// Source originals live in assets-src/images (not served, not bundled).
// Usage: npm run images

import sharp from 'sharp';
import { mkdir, writeFile, rm } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SRC_DIR = path.join(ROOT, 'assets-src', 'images');
const OUT_DIR = path.join(ROOT, 'public', 'images');
const TS_OUT = path.join(ROOT, 'src', 'data', 'images.ts');

const WIDTHS = [640, 1280];
const QUALITY = 78;

/** key in IMAGES map → { file: original file name, out: public base name } */
const SOURCES = [
  { key: 'sofaWarm', file: 'zone_sofa_warm_minimalism_1791271994705.jpg', out: 'sofa-warm' },
  { key: 'sofaLiving', file: 'zone_sofa_living_1791271622525.jpg', out: 'sofa-living' },
  { key: 'coffeeCorner', file: 'zone_coffee_corner_1791272009507.jpg', out: 'coffee-corner' },
  { key: 'coffeeCornerWide', file: 'zone_coffee_corner_1791271611901.jpg', out: 'coffee-corner-wide' },
  { key: 'workspaceDesk', file: 'zone_workspace_desk_1791272019797.jpg', out: 'workspace-desk' },
  { key: 'workspaceDeskWide', file: 'zone_workspace_desk_1791271634589.jpg', out: 'workspace-desk-wide' },
  { key: 'bedroomCalm', file: 'zone_bedroom_calm_1791272030072.jpg', out: 'bedroom-calm' },
  { key: 'pantryHero', file: 'hero_pantry_organization_1791019032860.jpg', out: 'pantry-hero' },
  { key: 'pantryBefore', file: 'before_after_pantry_1791019078336.jpg', out: 'pantry-before' },
  { key: 'kitchenAesthetic', file: 'category_kitchen_aesthetic_1791019045387.jpg', out: 'kitchen-aesthetic' },
  { key: 'wardrobeCapsule', file: 'category_wardrobe_capsule_1791019056141.jpg', out: 'wardrobe-capsule' },
  { key: 'spicesDrawer', file: 'idea_spices_drawer_1791019066641.jpg', out: 'spices-drawer' },
  { key: 'smallStudio', file: 'small_studio_space_1791271644326.jpg', out: 'small-studio' },
];

await rm(OUT_DIR, { recursive: true, force: true });
await mkdir(OUT_DIR, { recursive: true });

const entries = [];
let totalBytes = 0;

for (const { key, file, out } of SOURCES) {
  const input = path.join(SRC_DIR, file);
  const meta = await sharp(input).metadata();
  const variants = [];

  for (const target of WIDTHS) {
    const width = Math.min(target, meta.width);
    if (variants.some((v) => v.width === width)) continue;
    const name = `${out}-${width}.webp`;
    const info = await sharp(input)
      .resize({ width, withoutEnlargement: true })
      .webp({ quality: QUALITY, effort: 5 })
      .toFile(path.join(OUT_DIR, name));
    variants.push({ name, width, height: info.height, size: info.size });
    totalBytes += info.size;
  }

  const largest = variants[variants.length - 1];
  entries.push({
    key,
    src: `/images/${largest.name}`,
    srcSet: variants.map((v) => `/images/${v.name} ${v.width}w`).join(', '),
    width: largest.width,
    height: largest.height,
  });
  console.log(`${file} → ${variants.map((v) => `${v.name} (${Math.round(v.size / 1024)} KB)`).join(', ')}`);
}

const ts = [
  '// Generated by scripts/optimize-images.mjs. Do not edit by hand; run `npm run images`.',
  "import type { ImageAsset } from '../types.ts';",
  '',
  'export const IMAGES = {',
  ...entries.map(
    (e) =>
      `  ${e.key}: { src: '${e.src}', srcSet: '${e.srcSet}', width: ${e.width}, height: ${e.height} },`
  ),
  '} satisfies Record<string, ImageAsset>;',
  '',
  'export type ImageKey = keyof typeof IMAGES;',
  '',
].join('\n');

await writeFile(TS_OUT, ts);
console.log(`\nWrote ${entries.length} images, ${Math.round(totalBytes / 1024)} KB total → ${path.relative(ROOT, TS_OUT)}`);
