// Core domain types for HomeEstet.
import type { ShopCategoryId } from './data/shopCategories.ts';

/** A responsive image generated by scripts/optimize-images.mjs */
export interface ImageAsset {
  src: string;
  srcSet: string;
  width: number;
  height: number;
}

/** Everything the zone wizard needs to (re)generate a solution. Serialisable, used in URLs and localStorage. */
export interface SolutionParams {
  zoneId: string;
  styleId: string;
  moodId: string;
  budgetId: string;
  existingItems: string[];
}

export type PageView =
  | { type: 'home' }
  | { type: 'analyze'; planId?: string }
  | { type: 'zone-builder'; zoneId?: string; prefilledStyle?: string; params?: SolutionParams }
  | { type: 'style-quiz' }
  | { type: 'small-spaces' }
  | { type: 'rented-home' }
  | { type: 'personal-plan' }
  | { type: 'inspiration'; articleId?: string }
  | { type: 'my-homeestet' };

export interface Zone {
  id: string;
  name: string;
  icon: string;
  description: string;
  image: ImageAsset;
  tagline: string;
  /** Items a user is likely to already own in this zone (shown as checkboxes). */
  commonExistingItems: string[];
  /** Items pre-checked by default for this zone. */
  defaultExistingItems: string[];
}

export interface InteriorStyle {
  id: string;
  name: string;
  uaName: string;
  description: string;
  keyFeatures: string[];
  colors: string[];
  materials: string[];
  image: ImageAsset;
  recommendedFor: string;
}

export interface Mood {
  id: string;
  label: string;
  icon: string;
  desc: string;
}

export interface BudgetTier {
  id: string;
  label: string;
  /** Upper limit in UAH used by the solution engine. */
  limit: number;
  desc: string;
}

export interface ProductItem {
  id: string;
  name: string;
  category: string;
  price: number;
  oldPrice?: number;
  rating?: number;
  reviewsCount?: number;
  description?: string;
  budgetAlternativePrice?: number;
  budgetAlternativeName?: string;
  freeAlternativeTip?: string;
  reason?: string;
  merchant: string;
  image: ImageAsset;
  /** Real store URL. Undefined until the partner catalogue is launched. */
  affiliateUrl?: string;
  zones: string[];
  styles: string[];
  moods: string[];
  tags: string[];
  /** Lower-case keywords of "what I already have" items that make this product redundant. */
  coversItems: string[];
  /** 1 = biggest impact on the space, 3 = finishing touch. */
  priority: 1 | 2 | 3;
  inStock?: boolean;
  canTakeWhenMoving?: boolean;
}

export interface SolutionStep {
  number: string;
  title: string;
  description: string;
  impact: string;
}

export interface ZoneSolution {
  /** Deterministic: the same params always produce the same id. */
  id: string;
  params: SolutionParams;
  zoneId: string;
  zoneName: string;
  zoneIcon: string;
  styleId: string;
  styleName: string;
  moodId: string;
  moodName: string;
  budgetId: string;
  budgetName: string;
  budgetLimit: number;
  existingItems: string[];
  conceptImage: ImageAsset;
  tagline: string;
  steps: SolutionStep[];
  /** Products that fit the budget, at most 4. */
  products: ProductItem[];
  estimatedCost: number;
  cheaperCost: number;
  /** True when fewer products fit the budget than a full makeover needs. */
  isPartial: boolean;
  /** True when too few products matched the style and the style filter was relaxed. */
  relaxedStyle: boolean;
  /** Products skipped because the user already owns an equivalent. */
  skippedOwned: ProductItem[];
  /** Matching products that did not fit the budget. */
  overBudget: ProductItem[];
  freeTips: string[];
  renterFriendly: boolean;
}

export interface SmallSpaceSolution {
  id: string;
  subcategory: string;
  title: string;
  areaLabel: string;
  problem: string;
  solution: string;
  image: ImageAsset;
  budget: number;
  products: ProductItem[];
  freeAlternative: string;
  keyTakeaway: string;
}

export interface RentedHomeSolution {
  id: string;
  title: string;
  restriction: string;
  whatChanged: string[];
  beforeImage: ImageAsset;
  afterImage: ImageAsset;
  cost: number;
  canTakeWhenMoving: boolean;
  takeawayTips: string;
  products: ProductItem[];
}

export interface PlanTask {
  id: string;
  week: 1 | 2 | 3 | 4;
  weekTitle: string;
  category: string;
  title: string;
  description: string;
  estimatedMinutes: number;
  costEstimate: number;
}

export interface SurpriseIdea {
  id: string;
  title: string;
  whyItWorks: string;
  whatYouNeed: string;
  estimatedBudget: string;
  isFree: boolean;
  zoneHint: string;
  /** Zone to open in the wizard for "try it today". */
  zoneId?: string;
}

export interface ArticleIdeaSection {
  step: number;
  title: string;
  description: string;
  image: ImageAsset;
  imageAlt?: string;
  products: ProductItem[];
}

export interface BeforeAfterData {
  title: string;
  subtitle: string;
  beforeImg: ImageAsset;
  afterImg: ImageAsset;
  beforeLabel?: string;
  afterLabel?: string;
  notes?: string;
  changes?: string[];
  budget?: number;
  budgetFrom?: number;
}

export interface Article {
  id: string;
  slug: string;
  title: string;
  categoryId: string;
  categoryLabel: string;
  tags: string[];
  excerpt: string;
  readTime: string;
  date: string;
  author: {
    name: string;
    role: string;
  };
  coverImage: ImageAsset;
  intro: string;
  sections: ArticleIdeaSection[];
  beforeAfter?: BeforeAfterData;
  relatedArticleIds: string[];
  /** Zone the "make this zone" CTA should open. */
  zoneId: string;
}

// ---- Persisted user data (localStorage) ----

export interface SavedSolution {
  kind: 'solution';
  id: string;
  title: string;
  zoneId: string;
  zoneName: string;
  styleId: string;
  styleName: string;
  budgetId: string;
  budgetName: string;
  estimatedCost: number;
  params: SolutionParams;
  savedAt: string;
}

export interface SavedIdea {
  kind: 'idea';
  id: string;
  ideaId: string;
  title: string;
  zoneHint: string;
  zoneId?: string;
  estimatedBudget: string;
  savedAt: string;
}

export type SavedItem = SavedSolution | SavedIdea;

export interface PlanEntryTask {
  id: string;
  title: string;
  description: string;
}

export interface PlanEntry {
  id: string;
  title: string;
  zoneId: string;
  zoneName: string;
  tasks: PlanEntryTask[];
  productIds: string[];
  budget: number;
  status: 'active' | 'done';
  addedAt: string;
  params?: SolutionParams;
}

export interface PlanState {
  completedTaskIds: string[];
  entries: PlanEntry[];
}

export interface Preferences {
  styleId?: string;
}

export interface QuizResult {
  primaryStyleId: string;
  secondaryStyleId?: string;
  scores: Record<string, number>;
  answers: Record<string, string>;
  completedAt: string;
}

// ---- Photo analysis ("Фото → план") ----

/** What the user sends together with the photo. */
export interface AnalyzeParams {
  budgetId: string;
  /** Rented home: no drilling, painting or replacing the landlord's furniture. */
  rental: boolean;
  /** Optional free-text note from the user (what bothers them, constraints). */
  note?: string;
}

export interface PhotoPlanStep {
  title: string;
  description: string;
  impact: string;
}

export interface PhotoPlanProduct {
  id: string;
  reason: string;
}

/** One category the analysis suggests adding; the client shows several real products for it. */
export interface PhotoPlanShopping {
  category: ShopCategoryId;
  /** One sentence from the model: why this kind of thing helps this corner. */
  why: string;
}

/** Normalised analysis result the client renders. Produced server-side from the model output. */
export interface PhotoPlan {
  /** False when the photo does not show an interior; then only `summary` is meaningful. */
  isInterior: boolean;
  /** Zone id from ZONES, or null when the model could not map the room to a zone. */
  zoneId: string | null;
  zoneLabel: string;
  currentStyle: string;
  /** Style id from STYLES the room could grow into. */
  suggestedStyleId: string;
  palette: string[];
  materials: string[];
  /** 0–100, how visually noisy the space is. */
  noiseLevel: number;
  noiseComment: string;
  problems: string[];
  remove: string[];
  rearrange: string[];
  useOwned: string[];
  steps: PhotoPlanStep[];
  /** Products from the catalogue that fit the budget, at most 4. */
  products: PhotoPlanProduct[];
  /** Sum of the selected products' prices. */
  estimatedCost: number;
  /** 2–4 store categories to show variants for. Absent in analyses saved before October 2026. */
  shopping?: PhotoPlanShopping[];
  budgetLimit: number;
  budgetMin: number;
  budgetMax: number;
  summary: string;
  confidence: 'low' | 'medium' | 'high';
}

export interface AnalyzeResponse {
  plan: PhotoPlan;
  model: string;
  usage: { inputTokens: number; outputTokens: number };
}

export interface SavedPhotoPlan {
  id: string;
  createdAt: string;
  /** Small JPEG data URL of the analysed photo for the saved list. */
  thumbnail: string;
  params: AnalyzeParams;
  plan: PhotoPlan;
}

export type ShopStore = 'sinsay' | 'epicentr';

/** A real product from a partner store (generated catalogue in src/data/shopCatalog.ts). */
export interface ShopProduct {
  id: string;
  name: string;
  category: ShopCategoryId;
  price: number;
  store: ShopStore;
  /** Product page in the store. Affiliate wrapping happens in lib/shop.ts. */
  url: string;
  /** Image on the store's CDN; the browser loads it directly, nothing is copied. */
  image: string;
  rating?: number;
  reviews?: number;
}
