// Generated by scripts/optimize-images.mjs. Do not edit by hand; run `npm run images`.
import type { ImageAsset } from '../types.ts';

export const IMAGES = {
  sofaWarm: { src: '/images/sofa-warm-1200.webp', srcSet: '/images/sofa-warm-640.webp 640w, /images/sofa-warm-1200.webp 1200w', width: 1200, height: 896 },
  sofaLiving: { src: '/images/sofa-living-1280.webp', srcSet: '/images/sofa-living-640.webp 640w, /images/sofa-living-1280.webp 1280w', width: 1280, height: 714 },
  coffeeCorner: { src: '/images/coffee-corner-1200.webp', srcSet: '/images/coffee-corner-640.webp 640w, /images/coffee-corner-1200.webp 1200w', width: 1200, height: 896 },
  coffeeCornerWide: { src: '/images/coffee-corner-wide-1280.webp', srcSet: '/images/coffee-corner-wide-640.webp 640w, /images/coffee-corner-wide-1280.webp 1280w', width: 1280, height: 714 },
  workspaceDesk: { src: '/images/workspace-desk-1200.webp', srcSet: '/images/workspace-desk-640.webp 640w, /images/workspace-desk-1200.webp 1200w', width: 1200, height: 896 },
  workspaceDeskWide: { src: '/images/workspace-desk-wide-1280.webp', srcSet: '/images/workspace-desk-wide-640.webp 640w, /images/workspace-desk-wide-1280.webp 1280w', width: 1280, height: 714 },
  bedroomCalm: { src: '/images/bedroom-calm-1200.webp', srcSet: '/images/bedroom-calm-640.webp 640w, /images/bedroom-calm-1200.webp 1200w', width: 1200, height: 896 },
  pantryHero: { src: '/images/pantry-hero-1280.webp', srcSet: '/images/pantry-hero-640.webp 640w, /images/pantry-hero-1280.webp 1280w', width: 1280, height: 714 },
  pantryBefore: { src: '/images/pantry-before-1280.webp', srcSet: '/images/pantry-before-640.webp 640w, /images/pantry-before-1280.webp 1280w', width: 1280, height: 714 },
  kitchenAesthetic: { src: '/images/kitchen-aesthetic-1200.webp', srcSet: '/images/kitchen-aesthetic-640.webp 640w, /images/kitchen-aesthetic-1200.webp 1200w', width: 1200, height: 896 },
  wardrobeCapsule: { src: '/images/wardrobe-capsule-1200.webp', srcSet: '/images/wardrobe-capsule-640.webp 640w, /images/wardrobe-capsule-1200.webp 1200w', width: 1200, height: 896 },
  spicesDrawer: { src: '/images/spices-drawer-1200.webp', srcSet: '/images/spices-drawer-640.webp 640w, /images/spices-drawer-1200.webp 1200w', width: 1200, height: 896 },
  smallStudio: { src: '/images/small-studio-1280.webp', srcSet: '/images/small-studio-640.webp 640w, /images/small-studio-1280.webp 1280w', width: 1280, height: 714 },
} satisfies Record<string, ImageAsset>;

export type ImageKey = keyof typeof IMAGES;
